name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.5
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Deploy to Server
      run: |
        rsync -avz --delete ./ chbe6dd198@hilux.cityhost.com.ua:/www/klas.it-volunteers.com/wp-content/themes/klas/
